### ISSUE TITLE
React - Build failure

### ISSUE THREAD

**Issue by mikkimichaelis** [auth0-samples/auth0-ionic-samples#442]
Good grief guys.......

So I’ve switched to the React app within this repo.  
Clone
configure auth.config.ts
npm i
ionic capacitor build ios
yields

> react-scripts build
Creating an optimized production build...
Failed to compile.

Module not found: Error: You attempted to import ../../capacitor.config which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/. 

Are you guys not even testing these repos anymore?  I noticed it was just updated yesterday, please attempt to use the provided code.

**Comment by frederikprijck** [comment]
Hey @mikkimichaelis ,

Thanks for reaching out, and sorry you've been experiencing difficulties running the sample.
I see you already closed the issue, would it be resolved?

Regardless, I did the following:

```
git clone git@github.com:auth0-samples/auth0-ionic-samples.git
cd auth0-ionic-samples/react
npm i
```
Next, I renamed `auth.config.ts.example` to `auth.config.ts` and update it to fill in my domain and clientId.
Then I run for iOS using

```
npx cap run ios
```
This opens the app in my iOS simulator, as expected.

> Our README mentions to use `npx cap` instead of `npx ionic capacitor`, so I used that to verify it works.
This runs the app fine. Can you verify it runs fine as well? Regardless, I would recommend to stick to what is being mentioned in the readme.


Next I tried building the application using capacitor:

```
npx cap build ios
```

This works for `building xArchive`, but fails on the `Building IPA` because of my xCode not being configured properly to sign this. However, it seems that compilation worked.

Would any of this help? If not, if you could provide a bit more information we are happy to look into this.

Thanks
