### ISSUE TITLE
React same app does not work

### ISSUE THREAD

**Issue by mikkimichaelis** [auth0-samples/auth0-ionic-samples#443]
Due to https://github.com/auth0-samples/auth0-ionic-samples/issues/442 I moved capacitor.confg.ts into src allowing to build for the iOS platform.

However the React sample app produces the same behavior as the Angular sample app (please see https://github.com/auth0-samples/auth0-ionic-samples/issues/441)

Here are the slightly different logs (vs  https://github.com/auth0-samples/auth0-ionic-samples/issues/441) produced by the sample.  No errors, Safari still remains open, and Auth0 does nothing.

⚡️  To Native ->  App addListener 38238715
⚡️  WebView loaded
⚡️  To Native ->  App addListener 38238716
⚡️  To Native ->  Browser open 38238717
2022-12-13 21:15:24.715582-0600 App[70777:2440177] Unbalanced calls to begin/end appearance transitions for <Capacitor.TmpViewController: 0x7fdb7250c3f0>.
⚡️  TO JS undefined
⚡️  TO JS {"url":"com.auth0.samples:\/\/xxxxxxxxxx.us.auth0.com\/capacitor\/com.auth0.samples\/callback?code=kl4tpQxus..........QdcUO1zs&state=cXdqTX5KZj.......b0JoOWgxTkpLRA%3D%3D","iosSourceApplication":”com.apple.Saf

Would Auth0 support be so kind as to supply a working React Ionic Auth0 sample app?

Thank you so much in advance.......

**Comment by frederikprijck** [comment]
As mentioned in https://github.com/auth0-samples/auth0-ionic-samples/issues/442#issuecomment-1350657026, the sample application seems to work fine on my end.

As I don't think you should be moving the `capacitor`'s config into the `src` directory (this is put in the root when creating a project using `npm init @capacitor/app` as per https://capacitorjs.com/docs/getting-started).

Let's focus on solving the original problem in https://github.com/auth0-samples/auth0-ionic-samples/issues/442, instead of those that show up based on the workaround being used.

**Comment by mikkimichaelis** [comment]
I found the problem, it was CORS.  that’s why I closed these issues
